import os, json, shutil
from fastapi import APIRouter, Body, HTTPException

router = APIRouter()
PROJECTS_DIR = os.path.abspath("projects")
os.makedirs(PROJECTS_DIR, exist_ok=True)

def project_path(name):
    return os.path.join(PROJECTS_DIR, name)

@router.get("/")
def list_projects():
    return {"projects": os.listdir(PROJECTS_DIR)}

@router.post("/create")
def create_project(name: str = Body(..., embed=True)):
    path = project_path(name)
    if os.path.exists(path):
        raise HTTPException(400, f"Project {name} already exists")
    os.makedirs(path)
    with open(os.path.join(path, "README.md"), "w") as f:
        f.write(f"# {name}\nGenerated by Atbott SaaS Project\n")
    return {"created": name}

@router.delete("/delete")
def delete_project(name: str = Body(..., embed=True)):
    path = project_path(name)
    if not os.path.exists(path):
        raise HTTPException(404, "Project not found")
    shutil.rmtree(path)
    return {"deleted": name}

@router.get("/open")
def open_project(name: str):
    path = project_path(name)
    if not os.path.exists(path):
        raise HTTPException(404, "Project not found")
    files = []
    for root, _, file_list in os.walk(path):
        for f in file_list:
            full = os.path.join(root, f)
            files.append(full.replace(PROJECTS_DIR + os.sep, ""))
    return {"project": name, "files": files}
